import Link from 'next/link';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <h1 className="text-center">Emojus</h1>
          <p className="text-center">Emojus is singular of emoji, right?</p>
          <p className="text-center">
            <Link href="https://github.com/OyvindSabo/emojus">GitHub</Link>
          </p>
        </header>
        <main className="p-4">{children}</main>
      </body>
    </html>
  );
}
